#draw heart 1
import turtle as t
import time
def drawheart(color) :
    t.pencolor(color)
    t.pensize(8)
    t.pendown()
    t.seth(130)
    t.circle(-80 , 220)
    t.seth(90)
    t.circle(-80 , 220)
    t.fd(220)
    t.seth(130)
    t.fd(220)
    t.penup()
    t.seth(0)
    t.fd(30)
    time.sleep(1)
t.speed(0)
drawheart('red')
drawheart('blue')
drawheart('yellow')
drawheart('green')
drawheart('pink')
t.penup()
t.goto(-100 , -10)
t.pendown()
t.pencolor('black')
t.fd(600)
t.hideturtle()
